version: '3'
services:
  web:
    image: sammrai/logflow
    ports:
      - "3000:3000"
    volumes:
    # Mount your log directory to /log
      - /path/to/your/log:/log
    environment:
      - LOG_FILE=/log/your-logfile.log
